get_parameters = function() {
  params = list(modelyear = 2024, ACC_LevyRate = 0.0153, ACC_MaxLeviableIncome = 139384, 
                Accommodation_AbatementRate = 0.25, Accommodation_BaseRateThreshold_Mortgage = 0.3, 
                Accommodation_BaseRateThreshold_Rent = 0.25, Accommodation_MaxRate_CoupleDeps_Single2_Deps_Area1 = 0, 
                Accommodation_MaxRate_CoupleDeps_Single2_Deps_Area2 = 0, 
                Accommodation_MaxRate_CoupleDeps_Single2_Deps_Area3 = 0, 
                Accommodation_MaxRate_CoupleDeps_Single2_Deps_Area4 = 0, 
                Accommodation_MaxRate_CoupleNoDeps_Single1Dep_Area1 = 0, 
                Accommodation_MaxRate_CoupleNoDeps_Single1Dep_Area2 = 0, 
                Accommodation_MaxRate_CoupleNoDeps_Single1Dep_Area3 = 0, 
                Accommodation_MaxRate_CoupleNoDeps_Single1Dep_Area4 = 0, 
                Accommodation_MaxRate_SingleNoDeps_Area1 = 165, Accommodation_MaxRate_SingleNoDeps_Area2 = 105, 
                Accommodation_MaxRate_SingleNoDeps_Area3 = 80, Accommodation_MaxRate_SingleNoDeps_Area4 = 70, 
                Accommodation_PaymentPercentage = 0.7, Benefits_JSS_AbatementScale = structure(c(0, 
                                                                                                 8352, 0, 0.7), dim = c(2L, 2L)), Benefits_JSS_CoupleAbatementScale = structure(c(0, 
                                                                                                                                                                                  8352, 0, 0.35), dim = c(2L, 2L)), Benefits_JSS_Rate_Couple = 287.35, 
                Benefits_JSS_Rate_CoupleParent = 303.43, Benefits_JSS_Rate_Single = 337.74, 
                Benefits_JSS_Rate_SoleParent = 472.79, Benefits_SPS_AbatementScale = structure(c(0, 
                                                                                                 8352, 13050, 0, 0.3, 0.7), dim = 3:2), Benefits_SPS_Rate = 472.79, 
                Benefits_Entitlement_Age_SPS_ChildLowerBound = 14, Benefits_WinterEnergy_Rates_Single = 450, 
                Benefits_WinterEnergy_Rates_CoupleOrDeps = 700, Benefits_LivingAlonePayment_Single = 0, 
                Benefits_LivingAlonePayment_SoleParent = 0, FamilyAssistance_Abatement_AbatementScale = structure(c(0, 
                                                                                                                    42700, 0, 0.27), dim = c(2L, 2L)), FamilyAssistance_Abatement_Order = 0, 
                FamilyAssistance_FTC_Rates_FirstChild = 7121, FamilyAssistance_FTC_Rates_SubsequentChild = 5802, 
                FamilyAssistance_IWTC_Rates_UpTo3Children = 3770, FamilyAssistance_IWTC_Rates_SubsequentChildren = 780, 
                FamilyAssistance_IWTC_Eligibility = 1, FamilyAssistance_FullTimeWorkingHours_Couple = 30, 
                FamilyAssistance_FullTimeWorkingHours_Single = 20, FamilyAssistance_IWTC_IncomeThreshold_Single = 1184.94, 
                FamilyAssistance_IWTC_IncomeThreshold_Couple = 1184.94, FamilyAssistance_IWTC_ToBeneficiaries = 0, 
                FamilyAssistance_IWTC_PhaseIn_Single = structure(c(0, 0), dim = 1:2), 
                FamilyAssistance_IWTC_PhaseIn_Couple = structure(c(0, 0), dim = 1:2), 
                FamilyAssistance_MFTC_Rates_MinimumIncome = 34216, FamilyAssistance_BestStart_Abatement_AbatementScale = structure(c(0, 
                                                                                                                                     79000, 0, 0.21), dim = c(2L, 2L)), FamilyAssistance_BestStart_Rates_Age0 = 3632, 
                FamilyAssistance_BestStart_Rates_Age1or2 = 3632, IETC_AbatementScale = structure(c(0, 
                                                                                                   44000, 0, 0.13), dim = c(2L, 2L)), IETC_MinimalIncome = 24000, 
                IETC_PerYear = 520, IETC_OnlyFamiliesWithoutChildren = 0, 
                EITC_ApplyEITC = 0, EITC_AbatementScale = structure(c(0, 
                                                                      0, 0, 0), dim = c(2L, 2L)), EITC_ExcludeFamiliesWithoutChildren = 0, 
                Tax_BaseScale = structure(c(0, 14000, 48000, 70000, 180000, 
                                            0.105, 0.175, 0.3, 0.33, 0.39), dim = c(5L, 2L)))
  return(params)
}